##.title
## â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“
##
## ðŸ‡½ðŸ‡¾ðŸ‡¿ & Dev
##
## Copyright â’¸ Robert Mollentze, xyzand.dev
## 
## Licensing details can be found in the LICENSE file in the root directory.
## 
## â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“
##.title~

name: _data
publish_to: none

## -----------------------------------------------------------------------------

environment:

  sdk: '>=3.0.0 <4.0.0'

## -----------------------------------------------------------------------------

dependencies:

  flutter:
    sdk: flutter

  xyz_config: ^0.24.0
  xyz_gen_annotations: ^0.15.0
  xyz_utils: ^0.51.0

  uuid: 4.3.3

## -----------------------------------------------------------------------------

dev_dependencies:

  flutter_lints: any